services:
  postgres:
    image: postgres:latest
    container_name: postgres-exam
    environment:
      POSTGRES_USER: test-admin
      POSTGRES_PASSWORD: test-password
    volumes:
      - .C:/Adrian/Universidad/9no Semestre/1. Wed. - Integración de Sistemas/AB-Ex_Progreso_2/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  microservice:
    build:
      context: ./Microservice/room
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - app-network

  restservice:
    build:
      context: ./REST_Service/reservation
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  soapservice:
    build:
      context: ./SOAP_service/availability
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
